### ISSUE TITLE
Conflict with RandyKnapp's EpicLoot

### ISSUE THREAD

**Issue by melchitherabbit** [TwentyOneZ/Vegvisir_Directions#1]
Great mod! I just wanted to report a conflict with popular EpicLoot mod by RandyKnapp. Namely if you have it installed only two status effects, Rested and Resting, bring up map with restriction on.

[EDIT] This can be resolved upon finding the exact status effect name (in EpicLoot "Wishbone" gets "CustomWishboneFinder" id).
[EDIT EDIT] WHICH proves wrong the op comment on any conflict there...

**Comment by TwentyOneZ** [comment]
Haha! I just tested it out and it indeed works using "CustomWishboneFinder" id. 

Well... I guess that's it! Thanks for solving this one!

**Comment by TwentyOneZ** [comment]
To resolve the issue of Wishbone status not working on map restrictions when also using EpicLoot mod, set the following option in the twentyOneZ.VegvisirDirections.cfg file:
`Map enabled with this effect = CustomWishboneFinder`
Thanks to [melchitherabbit](https://github.com/melchitherabbit) for this one!
